### ISSUE TITLE
concurrent.futures.process._RemoteTraceback - When using jobs

### ISSUE THREAD

**Issue by rhurup** [vincrichard/VobSub-ML-OCR#1]
Hi :)

I'm facing some small issues when using jobs: 

`
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/www/VobSub-main/vob_sub/custom_color.py", line 14, in __getattr__
    raise AttributeError("'%s' not found" % label)
AttributeError: 'get___getstate__' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/VobSub-main/vob_sub/custom_color.py", line 16, in __getattr__
    return getattr(self, 'get_' + label)()
  File "/var/www/VobSub-main/vob_sub/custom_color.py", line 20, in __getattr__
    return self.__dict__[label]
KeyError: 'get___getstate__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/var/www/VobSub-main/vob_sub/custom_color.py", line 20, in __getattr__
    return self.__dict__[label]
KeyError: '__getstate__'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/VobSub-main/main.py", line 77, in <module>
    main()
  File "/var/www/VobSub-main/main.py", line 73, in main
    launch(args.mode, sub_file, dest_folder, args.language, args.jobs)
  File "/var/www/VobSub-main/main.py", line 47, in launch
    image_paths = create_generate_sub_images(vob_sub_file_name, folder_imgs, n_jobs)
  File "/var/www/VobSub-main/main.py", line 10, in create_generate_sub_images
    subfile, image_paths = extract_vob_sub_img(vob_sub_file_name, folder_imgs, n_jobs)
  File "/var/www/VobSub-main/vob_sub/main.py", line 31, in extract_vob_sub_img
    return multiprocess(_vob_sub_merged_pack_list, folder_path, _palette, n_jobs)
  File "/var/www/VobSub-main/vob_sub/main.py", line 73, in multiprocess
    for result in tqdm(executor.map(
  File "/home/www-data/.local/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/var/www/VobSub-main/vob_sub/custom_color.py", line 20, in __getattr__
    return self.__dict__[label]
KeyError: '__getstate__'
`
![Screenshot 2024-11-09 at 18 19 14](https://github.com/user-attachments/assets/fe385d5a-8179-4791-a48e-69a51aa51804)

**Comment by vincrichard** [comment]
Hi @rhurup 
I haven't fully tested the parallel processing, from the error it seems that there are some issue when the colour object is being pickled. 
I made some hotfixes, but I can't really test them out now. Feel free to test the new version and tell me if it works. 
Otherwise, can't you use job=1 ? I believe the time was still manageable.
